[package]
name = "vectorama"
version = "0.1.0"
edition = "2024"

[dependencies]
approx = "0.5.1"
na033 = { version = "~0.33", package = "nalgebra", optional = true }
na034 = { version = "~0.34", package = "nalgebra", optional = true }

[features]
nalgebra_033 = ["na033"]
nalgebra_034 = ["na034"]