name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Clippy (deny warnings)
      run: cargo clippy --verbose -- -D warnings
    - name: Build with nalgebra
      run: cargo build --verbose --features nalgebra_033,nalgebra_034
    - name: Run tests with nalgebra
      run: cargo test --verbose --features nalgebra_033,nalgebra_034
    - name: Clippy with nalgebra (deny warnings)
      run: cargo clippy --verbose --features nalgebra_033,nalgebra_034 -- -D warnings
